export const STOCKS = ['American Airlines Group, Inc.',  
                        'Apple Inc.',  
                        'Adobe Inc.',  
                        'Analog Devices, Inc.',  
                        'Automatic Data Processing, Inc.',  
                        'Autodesk, Inc.',  
                        'Align Technology, Inc.',  
                        'Alexion Pharmaceuticals, Inc.',  
                        'Applied Materials, Inc.',  
                        'Amgen Inc.',  
                        'Amazon.com, Inc.',  
                        'ASML Holding N.V.',  
                        'Activision Blizzard, Inc',  
                        'Broadcom Inc.',  
                        'Baidu, Inc.',  
                        'Biogen Inc.',  
                        'Booking Holdings Inc.',  
                        'BioMarin Pharmaceutical Inc.',  
                        'Cadence Design Systems, Inc.',  
                        'Celgene Corporation',  
                        'Cerner Corporation',  
                        'Check Point Software Technologies Ltd.',  
                        'Charter Communications, Inc.',  
                        'Comcast Corporation',  
                        'Costco Wholesale Corporation',  
                        'Cisco Systems, Inc.',  
                        'CSX Corporation',  
                        'Cintas Corporation',  
                        'Ctrip.com International, Ltd.',  
                        'Cognizant Technology Solutions Corporation',  
                        'Citrix Systems, Inc.',  
                        'Dollar Tree, Inc.',  
                        'Electronic Arts Inc.',  
                        'eBay Inc.',  
                        'Express Scripts Holding Company',  
                        'Expedia Group, Inc.',  
                        'Fastenal Company',  
                        'Facebook, Inc.',  
                        'Fiserv, Inc.',  
                        'Twenty-First Century Fox, Inc.',  
                        'Twenty-First Century Fox, Inc.',  
                        'Gilead Sciences, Inc.',  
                        'Alphabet Inc.',  
                        'Alphabet Inc.',  
                        'Hasbro, Inc.',  
                        'Hologic, Inc.',  
                        'Henry Schein, Inc.',  
                        'IDEXX Laboratories, Inc.',  
                        'Illumina, Inc.',  
                        'Incyte Corporation',  
                        'Intel Corporation',  
                        'Intuit Inc.',  
                        'Intuitive Surgical, Inc.',  
                        'J.B. Hunt Transport Services, Inc.',  
                        'JD.com, Inc.',  
                        'The Kraft Heinz Company',  
                        'KLA-Tencor Corporation',  
                        'Liberty Global plc',  
                        'Liberty Global plc1'
]
